

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Sijan Bhandari
 */
public class Screen extends javax.swing.JFrame {

    /**
     * Creates new form Screen
     */
    public Screen() {
        initComponents();
       
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        ress = new javax.swing.JLabel();
        res1 = new javax.swing.JLabel();
        res2 = new javax.swing.JLabel();
        bsd = new rojeru_san.rsfield.RSTextFull();
        bsyy = new rojeru_san.rsfield.RSTextFull();
        bsmm = new rojeru_san.rsfield.RSTextFull();
        rSButtonRound1 = new rojeru_san.rsbutton.RSButtonRound();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        filec = new javax.swing.JFileChooser();
        filec1 = new javax.swing.JFileChooser();
        jPanel3 = new javax.swing.JPanel();
        resbulk = new javax.swing.JLabel();
        sep = new rojeru_san.rsfield.RSTextFull();
        rSButtonRound2 = new rojeru_san.rsbutton.RSButtonRound();
        se = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIjan's BS to AD");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 255));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ress.setFont(new java.awt.Font("Swis721 Hv BT", 1, 24)); // NOI18N
        ress.setForeground(new java.awt.Color(0, 0, 255));
        ress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(ress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 560, 70));

        res1.setFont(new java.awt.Font("Swis721 Hv BT", 1, 24)); // NOI18N
        res1.setForeground(new java.awt.Color(0, 0, 255));
        res1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        res1.setText("/");
        jPanel2.add(res1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 40, 70));

        res2.setFont(new java.awt.Font("Swis721 Hv BT", 1, 24)); // NOI18N
        res2.setForeground(new java.awt.Color(0, 0, 255));
        res2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        res2.setText("/");
        jPanel2.add(res2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 40, 70));

        bsd.setToolTipText("");
        bsd.setPlaceholder("day");
        jPanel2.add(bsd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 80, -1));

        bsyy.setToolTipText("");
        bsyy.setPlaceholder("Year");
        bsyy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsyyActionPerformed(evt);
            }
        });
        jPanel2.add(bsyy, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 110, -1));

        bsmm.setToolTipText("");
        bsmm.setPlaceholder("month");
        bsmm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsmmActionPerformed(evt);
            }
        });
        jPanel2.add(bsmm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 80, -1));

        rSButtonRound1.setText("Convert");
        rSButtonRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 160, 40));

        jTabbedPane1.addTab("Single Date", jPanel2);

        jTabbedPane2.addTab("Select File", filec);

        filec1.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        filec1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filec1ActionPerformed(evt);
            }
        });
        jTabbedPane2.addTab("Select file location to save", filec1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resbulk.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        resbulk.setForeground(new java.awt.Color(0, 0, 255));
        resbulk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(resbulk, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 500, 70));

        sep.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sep.setText("-");
        sep.setPlaceholder("separator");
        sep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sepActionPerformed(evt);
            }
        });
        jPanel3.add(sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 100, -1));

        rSButtonRound2.setText("Convert And Save");
        rSButtonRound2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound2ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 180, -1));

        se.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        se.setForeground(new java.awt.Color(0, 204, 204));
        se.setText("Separator");
        jPanel3.add(se, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 110, 30));

        jTabbedPane2.addTab("Bulk Date Converter", jPanel3);

        jTabbedPane1.addTab("Multiple Date", jTabbedPane2);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 610, 310));
        jTabbedPane1.getAccessibleContext().setAccessibleName("tab");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Sijan's BS to AD Calculator");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 300, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonHover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover1ActionPerformed
        
    }//GEN-LAST:event_rSButtonHover1ActionPerformed

    private void seppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seppActionPerformed

    private void rSButtonHover2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover2ActionPerformed


    }//GEN-LAST:event_rSButtonHover2ActionPerformed

    private void bsdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFull1ActionPerformed

    }//GEN-LAST:event_rSTextFull1ActionPerformed

    private void bsyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFull2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFull2ActionPerformed

    private void bsmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFull3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFull3ActionPerformed

    private void rSButtonRound2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound2ActionPerformed

        File bulk=filec.getSelectedFile();String bste,bst,ads;
        File p=new File(filec1.getSelectedFile().getPath()+".txt");
        try {
            p.createNewFile();
            BufferedReader bf=new BufferedReader(new FileReader(bulk));
            BufferedWriter bw=new BufferedWriter(new FileWriter(p));

            while((bste=bf.readLine())!=null){
                System.out.println("Date:"+bste);
                bst=intoEN(bste);
                System.out.println(bst);
                ads=converter.CalendarFunctions.main(bst,sep.getText());
                bw.write(ads);
                System.out.println(bst+">"+ads);
                bw.newLine();
                //bst=bf.readLine();
            }
            bf.close();
            bw.close();
            resbulk.setText("saved in "+p.getPath());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound2ActionPerformed

    private void sepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sepActionPerformed

    private void rSButtonRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound1ActionPerformed
        String res="/";
        String bs=bsyy.getText()+res+bsmm.getText()+res+bsd.getText();
        bs=intoEN(bs);
        System.out.println(bs);
        String ADT;
        try {
            ADT = converter.CalendarFunctions.main(bs, res);
            ress.setText(ADT);
        } catch (Exception ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound1ActionPerformed

    private void bsmmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsmmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bsmmActionPerformed

    private void bsyyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsyyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bsyyActionPerformed

    private void filec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filec1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filec1ActionPerformed

    
    String intoEN(String s){
        char[] c=s.toCharArray();
        for(int i=0;i<c.length;i++){
            switch(c[i]){
                case '०':
                    c[i]='0';
                    break;
                case '१':
                    c[i]='1';
                    break;
                case '२':
                    c[i]='2';
                    break;
                case '३':
                    c[i]='3';
                    break;
                case '४':
                    c[i]='4';
                    break;
                case '५':
                    c[i]='5';
                    break;
                case '६':
                    c[i]='6';
                    break;
                case '७':
                    c[i]='7';
                    break;
                case '८':
                    c[i]='8';
                    break;
                case '९':
                    c[i]='9';
                    break;
                default:
                   
                    
            }
        }
        System.out.println(c);
        return String.valueOf(c);
        
}



    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Screen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.rsfield.RSTextFull bsd;
    private rojeru_san.rsfield.RSTextFull bsmm;
    private rojeru_san.rsfield.RSTextFull bsyy;
    private javax.swing.JFileChooser filec;
    private javax.swing.JFileChooser filec1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound1;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound2;
    private javax.swing.JLabel res1;
    private javax.swing.JLabel res2;
    private javax.swing.JLabel resbulk;
    private javax.swing.JLabel ress;
    private javax.swing.JLabel se;
    private rojeru_san.rsfield.RSTextFull sep;
    // End of variables declaration//GEN-END:variables
}
